//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sms
    {
        public int SmsId { get; set; }
        public string SmsTitle { get; set; }
        public string SmsContent { get; set; }
        public System.DateTime Time { get; set; }
        public int SenderId { get; set; }
        public int ReciverId { get; set; }
    
        public virtual Simcard Simcard { get; set; }
        public virtual Simcard Simcard1 { get; set; }
    }
}
