//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff
    {
        public int TariffId { get; set; }
        public Nullable<decimal> CallTariff { get; set; }
        public Nullable<decimal> SmsTarrif { get; set; }
    }
}
